# Generated by Django 3.2.8 on 2021-10-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20211030_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
