# Generated by Django 3.2.8 on 2021-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_contactdetails_clinic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performed_surgeries', models.PositiveBigIntegerField(blank=True, null=True)),
                ('Satisfied_patients', models.PositiveBigIntegerField(blank=True, null=True)),
                ('StaffMembers', models.PositiveBigIntegerField(blank=True, null=True)),
                ('Yearly_surgeries', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
