# Generated by Django 3.2.8 on 2021-10-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('points', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
