# Generated by Django 3.2.8 on 2021-11-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_dashboardcontent_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcontent',
            name='faq_image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
