# Generated by Django 3.2.8 on 2021-11-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_dashboardcontent_faq_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dashboardcontent',
            name='faq_image',
        ),
        migrations.RemoveField(
            model_name='dashboardcontent',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='whatweoffer',
            name='points',
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='whatweoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='whatweoffer',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.description'),
        ),
    ]
