# Generated by Django 3.2.8 on 2021-11-14 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_auto_20211113_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='description',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='whatweoffer',
            old_name='title',
            new_name='offered_services',
        ),
        migrations.RemoveField(
            model_name='whatweoffer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='whatweoffer',
            name='image',
        ),
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='description',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.whatweoffer'),
        ),
    ]
