# Generated by Django 3.2.8 on 2021-11-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_auto_20211114_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='offer',
        ),
        migrations.AddField(
            model_name='whatweoffer',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.description'),
        ),
    ]
