# Generated by Django 3.2.8 on 2021-11-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_auto_20211114_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_image', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
        migrations.RemoveField(
            model_name='faq',
            name='faq_image',
        ),
    ]
