# Generated by Django 3.2.8 on 2021-11-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_alter_faq_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatweoffer',
            old_name='offered_services',
            new_name='our_services',
        ),
    ]
