# Generated by Django 3.2.8 on 2021-11-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_rename_offered_services_whatweoffer_our_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcontent',
            name='quote',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
