# Generated by Django 3.2.8 on 2021-11-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_dashboardcontent_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
