# Generated by Django 3.2.8 on 2021-11-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_bookingappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='closing_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='opening_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
