# Generated by Django 3.2.8 on 2021-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0018_auto_20211114_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='fb_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
