# Generated by Django 3.2.8 on 2021-12-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0023_fottericon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingAppointment',
        ),
    ]
