# Generated by Django 3.2.8 on 2021-12-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0024_delete_bookingappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
    ]
