# Generated by Django 3.2.8 on 2022-01-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(auto_now=True)),
                ('patient_name', models.CharField(max_length=2000)),
                ('preferred_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('martial_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Child', 'Child'), ('other', 'other')], max_length=2000)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=2000)),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zip', models.PositiveIntegerField(blank=True, null=True)),
                ('counrty', models.CharField(blank=True, max_length=2000, null=True)),
                ('home_number', models.PositiveIntegerField(blank=True, null=True)),
                ('work_number', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_number', models.PositiveIntegerField(blank=True, null=True)),
                ('reminder_via_message', models.BooleanField(default=False)),
                ('reminder_via_email', models.BooleanField(default=False)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('patient_employer', models.CharField(max_length=200)),
                ('patient_ocupation', models.CharField(max_length=200)),
                ('referal_name', models.CharField(max_length=200)),
                ('patient_relative_name', models.CharField(max_length=200)),
                ('patient_relative_number', models.PositiveIntegerField(blank=True, null=True)),
                ('relative_relationship', models.CharField(blank=True, max_length=2000, null=True)),
                ('relative_phone_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('guardian_dob', models.DateField(blank=True, null=True)),
                ('aids', models.BooleanField(default=False)),
                ('artifical_joints', models.BooleanField(default=False)),
                ('bloody_sputum', models.BooleanField(default=False)),
                ('bisphosphonate_medication', models.BooleanField(default=False)),
                ('cronic_cough', models.BooleanField(default=False)),
                ('epilepsy', models.BooleanField(default=False)),
                ('fainting', models.BooleanField(default=False)),
                ('growths', models.BooleanField(default=False)),
                ('high_blood_pressure', models.BooleanField(default=False)),
                ('heart_murmur', models.BooleanField(default=False)),
                ('hyper_thyroid', models.BooleanField(default=False)),
                ('Jaundice', models.BooleanField(default=False)),
                ('loss_appetite', models.BooleanField(default=False)),
                ('mitral_valve_prolapse', models.BooleanField(default=False)),
                ('nervous_disorders', models.BooleanField(default=False)),
                ('prosthetic_heart_valve', models.BooleanField(default=False)),
                ('respiratory_problems', models.BooleanField(default=False)),
                ('stomach_problems_ulcers', models.BooleanField(default=False)),
                ('Sexually_Transmitted_Diseases', models.BooleanField(default=False)),
                ('Unexplained_Weight_loss', models.BooleanField(default=False)),
            ],
        ),
    ]
