# Generated by Django 3.2.8 on 2022-01-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointments_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='martial_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Child', 'Child'), ('other', 'other')], max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient_employer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient_ocupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient_relative_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='referal_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
